import {
  useEffect,
  useMemo,
  useState,
  type ChangeEvent,
  type FormEvent,
  type ReactNode,
} from "react";

import {
  CheckCircle2,
  Eye,
  EyeOff,
  KeyRound,
  LockKeyhole,
  Mail,
  Phone,
  ShieldCheck,
  UserRound,
  X,
} from "lucide-react";

// =====================================================
// TYPES
// =====================================================

export type StaffRole =
  | "Doctor"
  | "Nurse"
  | "Receptionist"
  | "Housekeeper";

export interface UserFormData {
  full_name: string;
  email: string;
  password: string;
  pin: string;

  // Kept for compatibility with existing Staff.tsx.
  // Employee ID is generated by the backend.
  employee_id?: string;

  mobile?: string;
  shift?: string;
}

interface Props {
  role: StaffRole;
  initialData?: UserFormData;
  isEdit?: boolean;
  loading?: boolean;
  onSubmit: (
    data: UserFormData,
  ) => void | Promise<void>;
  onCancel: () => void;
}

// =====================================================
// CONSTANTS
// =====================================================

const SHIFT_OPTIONS = [
  "Morning",
  "Afternoon",
  "Evening",
  "Night",
] as const;

const DEFAULT_FORM: UserFormData = {
  full_name: "",
  email: "",
  password: "",
  pin: "",
  employee_id: "",
  mobile: "",
  shift: "Morning",
};

// =====================================================
// HELPERS
// =====================================================

function getRoleDescription(
  role: StaffRole,
): string {
  switch (role) {
    case "Doctor":
      return "Clinical staff account";

    case "Nurse":
      return "Nursing & patient care account";

    case "Receptionist":
      return "Front desk & patient support account";

    case "Housekeeper":
      return "Housekeeping & room operations account";

    default:
      return "Hospital staff account";
  }
}

// =====================================================
// PAGE
// =====================================================

export default function UserForm({
  role,
  initialData,
  isEdit = false,
  loading = false,
  onSubmit,
  onCancel,
}: Props) {
  const [form, setForm] =
    useState<UserFormData>(
      initialData ?? DEFAULT_FORM,
    );

  const [showPassword, setShowPassword] =
    useState(false);

  const [showPin, setShowPin] =
    useState(false);

  const [errors, setErrors] =
    useState<
      Record<
        keyof UserFormData,
        string
      >
    >({
      full_name: "",
      email: "",
      password: "",
      pin: "",
      employee_id: "",
      mobile: "",
      shift: "",
    });

  const [submitting, setSubmitting] =
    useState(false);

  // ===================================================
  // INITIAL DATA
  // ===================================================

  useEffect(() => {
    setForm({
      ...DEFAULT_FORM,
      ...(initialData ?? {}),
      password:
        initialData?.password ?? "",
      pin:
        initialData?.pin ?? "",
      shift:
        initialData?.shift ||
        "Morning",
    });

    setErrors({
      full_name: "",
      email: "",
      password: "",
      pin: "",
      employee_id: "",
      mobile: "",
      shift: "",
    });

    setShowPassword(false);
    setShowPin(false);
  }, [
    initialData,
    isEdit,
    role,
  ]);

  // ===================================================
  // PASSWORD STRENGTH
  // ===================================================

  const passwordStrength =
    useMemo(() => {
      const password =
        form.password;

      if (!password) {
        return {
          level: 0,
          label: "",
        };
      }

      let level = 0;

      if (password.length >= 8) {
        level += 1;
      }

      if (/[A-Z]/.test(password)) {
        level += 1;
      }

      if (/[a-z]/.test(password)) {
        level += 1;
      }

      if (/[0-9]/.test(password)) {
        level += 1;
      }

      if (
        /[^A-Za-z0-9]/.test(
          password,
        )
      ) {
        level += 1;
      }

      if (level >= 5) {
        return {
          level: 4,
          label: "Excellent",
        };
      }

      if (level >= 4) {
        return {
          level: 4,
          label: "Strong",
        };
      }

      if (level >= 3) {
        return {
          level: 3,
          label: "Good",
        };
      }

      if (level >= 2) {
        return {
          level: 2,
          label: "Fair",
        };
      }

      return {
        level: 1,
        label: "Weak",
      };
    }, [form.password]);

  // ===================================================
  // CHANGE
  // ===================================================

  const handleChange = (
    event: ChangeEvent<HTMLInputElement>,
  ) => {
    const {
      name,
      value,
    } = event.target;

    // -------------------------------------------------
    // PIN
    // -------------------------------------------------

    if (name === "pin") {
      const digitsOnly =
        value
          .replace(/\D/g, "")
          .slice(0, 6);

      setForm(
        (previous) => ({
          ...previous,
          pin: digitsOnly,
        }),
      );

      setErrors(
        (previous) => ({
          ...previous,
          pin: "",
        }),
      );

      return;
    }

    // -------------------------------------------------
    // MOBILE
    // -------------------------------------------------

    if (name === "mobile") {
      const digitsOnly =
        value
          .replace(/\D/g, "")
          .slice(0, 10);

      setForm(
        (previous) => ({
          ...previous,
          mobile: digitsOnly,
        }),
      );

      setErrors(
        (previous) => ({
          ...previous,
          mobile: "",
        }),
      );

      return;
    }

    // -------------------------------------------------
    // NORMAL INPUT
    // -------------------------------------------------

    setForm(
      (previous) => ({
        ...previous,
        [name]: value,
      }),
    );

    setErrors(
      (previous) => ({
        ...previous,
        [name]: "",
      }),
    );
  };

  // ===================================================
  // VALIDATION
  // ===================================================

  const validate = () => {
    const nextErrors: Record<
      keyof UserFormData,
      string
    > = {
      full_name: "",
      email: "",
      password: "",
      pin: "",
      employee_id: "",
      mobile: "",
      shift: "",
    };

    let valid = true;

    // -------------------------------------------------
    // FULL NAME
    // -------------------------------------------------

    if (!form.full_name.trim()) {
      nextErrors.full_name =
        "Full name is required.";

      valid = false;
    } else if (
      form.full_name.trim().length < 2
    ) {
      nextErrors.full_name =
        "Enter a valid full name.";

      valid = false;
    }

    // -------------------------------------------------
    // EMAIL — OPTIONAL
    // -------------------------------------------------

    if (form.email.trim()) {
      if (
        !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(
          form.email.trim(),
        )
      ) {
        nextErrors.email =
          "Enter a valid email address.";

        valid = false;
      }
    }

    // -------------------------------------------------
    // MOBILE — OPTIONAL
    // -------------------------------------------------

    if (form.mobile?.trim()) {
      if (
        !/^\d{10}$/.test(
          form.mobile.trim(),
        )
      ) {
        nextErrors.mobile =
          "Enter a valid 10-digit mobile number.";

        valid = false;
      }
    }

    // -------------------------------------------------
    // SHIFT
    // -------------------------------------------------

    // Shift is optional.
    // Morning is used as the default.

    // -------------------------------------------------
    // PASSWORD — OPTIONAL
    //
    // IMPORTANT:
    // If password is entered, ALL password
    // requirements become compulsory.
    // -------------------------------------------------

    if (form.password.trim()) {
      if (form.password.length < 8) {
        nextErrors.password =
          "Password must contain at least 8 characters.";

        valid = false;
      } else if (
        !/[A-Z]/.test(
          form.password,
        )
      ) {
        nextErrors.password =
          "Password must contain at least one uppercase letter.";

        valid = false;
      } else if (
        !/[a-z]/.test(
          form.password,
        )
      ) {
        nextErrors.password =
          "Password must contain at least one lowercase letter.";

        valid = false;
      } else if (
        !/[0-9]/.test(
          form.password,
        )
      ) {
        nextErrors.password =
          "Password must contain at least one number.";

        valid = false;
      }
    }

    // -------------------------------------------------
    // PIN — REQUIRED ON CREATE
    // -------------------------------------------------

    if (!isEdit) {
      if (!form.pin.trim()) {
        nextErrors.pin =
          "Security PIN is required.";

        valid = false;
      } else if (
        !/^\d{4,6}$/.test(
          form.pin,
        )
      ) {
        nextErrors.pin =
          "PIN must contain 4 to 6 digits.";

        valid = false;
      }
    }

    setErrors(
      nextErrors,
    );

    return valid;
  };

  // ===================================================
  // SUBMIT
  // ===================================================

  const handleSubmit = async (
    event: FormEvent<HTMLFormElement>,
  ) => {
    event.preventDefault();

    if (
      submitting ||
      loading
    ) {
      return;
    }

    if (!validate()) {
      return;
    }

    try {
      setSubmitting(true);

      await onSubmit({
        full_name:
          form.full_name.trim(),

        // Optional email.
        email:
          form.email.trim()
            ? form.email
                .trim()
                .toLowerCase()
            : "",

        // Optional password.
        // Backend handles blank password.
        password:
          form.password,

        // Required PIN during creation.
        pin:
          form.pin,

        // Never manually generate Employee ID
        // on the frontend.
        employee_id:
          undefined,

        // Optional mobile.
        mobile:
          form.mobile?.trim() ||
          undefined,

        shift:
          form.shift?.trim() ||
          undefined,
      });
    } finally {
      setSubmitting(false);
    }
  };

  // ===================================================
  // FIELD STYLE
  // ===================================================

  const inputClass = (
    field: keyof UserFormData,
  ) => `
    h-11
    w-full
    rounded-xl
    border
    bg-slate-50
    px-3
    text-sm
    text-slate-800
    outline-none
    transition
    placeholder:text-slate-400
    focus:bg-white
    focus:ring-4
    ${
      errors[field]
        ? `
          border-rose-300
          focus:border-rose-400
          focus:ring-rose-500/10
        `
        : `
          border-slate-200
          focus:border-blue-400
          focus:ring-blue-500/10
        `
    }
  `;

  // ===================================================
  // RENDER
  // ===================================================

  return (
    <form
      onSubmit={
        handleSubmit
      }
      className="
        flex
        max-h-[calc(100vh-140px)]
        flex-col
      "
    >
      {/* =================================================
          HEADER
      ================================================= */}

      <div
        className="
          shrink-0
          border-b
          border-slate-100
          px-6
          pb-5
        "
      >
        <div className="flex items-center gap-3">
          <div
            className="
              flex
              h-10
              w-10
              shrink-0
              items-center
              justify-center
              rounded-xl
              bg-blue-50
              text-blue-600
            "
          >
            <UserRound
              size={18}
            />
          </div>

          <div className="min-w-0">
            <h2
              className="
                text-base
                font-bold
                text-slate-900
              "
            >
              {isEdit
                ? `Edit ${role}`
                : `Create ${role} Account`}
            </h2>

            <p
              className="
                mt-0.5
                text-[11px]
                text-slate-400
              "
            >
              {getRoleDescription(
                role,
              )}
            </p>
          </div>
        </div>
      </div>

      {/* =================================================
          FORM BODY
      ================================================= */}

      <div
        className="
          min-h-0
          flex-1
          overflow-y-auto
          px-6
          py-5
        "
      >
        <div className="space-y-5">

          {/* =================================================
              BASIC INFORMATION
          ================================================= */}

          <section>
            <SectionHeading
              title="Basic Information"
              description="Identity and optional contact details."
            />

            <div
              className="
                mt-4
                grid
                gap-4
                sm:grid-cols-2
              "
            >
              {/* FULL NAME */}

              <FormField
                label="Full Name"
                required
                error={
                  errors.full_name
                }
                icon={UserRound}
              >
                <input
                  name="full_name"
                  value={
                    form.full_name
                  }
                  onChange={
                    handleChange
                  }
                  placeholder="Enter full name"
                  className={
                    inputClass(
                      "full_name",
                    )
                  }
                  autoComplete="name"
                  disabled={
                    submitting ||
                    loading
                  }
                />
              </FormField>

              {/* EMAIL */}

              <FormField
                label="Email Address"
                error={
                  errors.email
                }
                icon={Mail}
              >
                <input
                  type="email"
                  name="email"
                  value={
                    form.email
                  }
                  onChange={
                    handleChange
                  }
                  placeholder="Optional"
                  className={
                    inputClass(
                      "email",
                    )
                  }
                  autoComplete="email"
                  disabled={
                    submitting ||
                    loading
                  }
                />

                <p
                  className="
                    mt-1.5
                    text-[10px]
                    text-slate-400
                  "
                >
                  Optional. Leave blank if
                  the staff member does not
                  have an email address.
                </p>
              </FormField>

              {/* MOBILE */}

              <FormField
                label="Mobile Number"
                error={
                  errors.mobile
                }
                icon={Phone}
              >
                <input
                  type="tel"
                  name="mobile"
                  value={
                    form.mobile ??
                    ""
                  }
                  onChange={
                    handleChange
                  }
                  placeholder="Optional 10-digit mobile number"
                  inputMode="numeric"
                  maxLength={10}
                  className={
                    inputClass(
                      "mobile",
                    )
                  }
                  autoComplete="tel"
                  disabled={
                    submitting ||
                    loading
                  }
                />

                <p
                  className="
                    mt-1.5
                    text-[10px]
                    text-slate-400
                  "
                >
                  Optional. Leave blank if
                  unavailable.
                </p>
              </FormField>

              {/* SHIFT */}

              <FormField
                label="Shift"
                error={
                  errors.shift
                }
              >
                <select
                  name="shift"
                  value={
                    form.shift ||
                    "Morning"
                  }
                  onChange={(
                    event,
                  ) => {
                    setForm(
                      (
                        previous,
                      ) => ({
                        ...previous,
                        shift:
                          event
                            .target
                            .value,
                      }),
                    );

                    setErrors(
                      (
                        previous,
                      ) => ({
                        ...previous,
                        shift:
                          "",
                      }),
                    );
                  }}
                  className={`
                    ${inputClass(
                      "shift",
                    )}
                    appearance-none
                  `}
                  disabled={
                    submitting ||
                    loading
                  }
                >
                  {SHIFT_OPTIONS.map(
                    (
                      shift,
                    ) => (
                      <option
                        key={
                          shift
                        }
                        value={
                          shift
                        }
                      >
                        {shift}
                      </option>
                    ),
                  )}
                </select>
              </FormField>
            </div>

            {/* AUTO EMPLOYEE ID NOTICE */}

            {!isEdit && (
              <div
                className="
                  mt-4
                  flex
                  items-start
                  gap-3
                  rounded-2xl
                  border
                  border-slate-100
                  bg-slate-50/70
                  p-4
                "
              >
                <div
                  className="
                    flex
                    h-8
                    w-8
                    shrink-0
                    items-center
                    justify-center
                    rounded-lg
                    bg-white
                    text-blue-600
                    shadow-sm
                  "
                >
                  <ShieldCheck
                    size={16}
                  />
                </div>

                <div>
                  <p
                    className="
                      text-[11px]
                      font-bold
                      text-slate-700
                    "
                  >
                    Employee ID generated automatically
                  </p>

                  <p
                    className="
                      mt-0.5
                      text-[10px]
                      leading-4
                      text-slate-400
                    "
                  >
                    HospitaX will automatically
                    assign the next available
                    employee ID for this staff
                    role.
                  </p>
                </div>
              </div>
            )}
          </section>

          {/* =================================================
              SECURITY
          ================================================= */}

          <section>
            <SectionHeading
              title="Account Security"
              description="Login credentials for this staff account."
            />

            <div className="mt-4 space-y-4">

              {/* PASSWORD */}

              <FormField
                label="Password"
                required={false}
                error={
                  errors.password
                }
                icon={LockKeyhole}
              >
                <div className="relative">
                  <input
                    type={
                      showPassword
                        ? "text"
                        : "password"
                    }
                    name="password"
                    value={
                      form.password
                    }
                    onChange={
                      handleChange
                    }
                    placeholder={
                      isEdit
                        ? "Leave blank to keep current password"
                        : "Optional password"
                    }
                    className={`
                      ${inputClass(
                        "password",
                      )}
                      pr-11
                    `}
                    autoComplete="new-password"
                    disabled={
                      submitting ||
                      loading
                    }
                  />

                  <button
                    type="button"
                    onClick={() =>
                      setShowPassword(
                        (
                          value,
                        ) =>
                          !value,
                      )
                    }
                    className="
                      absolute
                      right-2
                      top-1/2
                      flex
                      h-8
                      w-8
                      -translate-y-1/2
                      items-center
                      justify-center
                      rounded-lg
                      text-slate-400
                      transition
                      hover:bg-slate-100
                      hover:text-slate-600
                    "
                    tabIndex={-1}
                    aria-label={
                      showPassword
                        ? "Hide password"
                        : "Show password"
                    }
                  >
                    {showPassword ? (
                      <EyeOff
                        size={16}
                      />
                    ) : (
                      <Eye
                        size={16}
                      />
                    )}
                  </button>
                </div>

                <p
                  className="
                    mt-1.5
                    text-[10px]
                    text-slate-400
                  "
                >
                  Optional. If a password is
                  provided, it must satisfy all
                  security requirements.
                </p>

                {/* PASSWORD STRENGTH */}

                {form.password && (
                  <div className="mt-2.5">
                    <div className="flex items-center justify-between">
                      <span
                        className="
                          text-[10px]
                          font-semibold
                          text-slate-400
                        "
                      >
                        Password strength
                      </span>

                      <span
                        className={`
                          text-[10px]
                          font-bold
                          ${
                            passwordStrength.level >=
                            4
                              ? "text-emerald-600"
                              : passwordStrength.level >=
                                3
                              ? "text-blue-600"
                              : passwordStrength.level >=
                                2
                              ? "text-amber-600"
                              : "text-rose-600"
                          }
                        `}
                      >
                        {
                          passwordStrength.label
                        }
                      </span>
                    </div>

                    <div className="mt-1.5 flex gap-1">
                      {[1, 2, 3, 4].map(
                        (
                          level,
                        ) => (
                          <div
                            key={
                              level
                            }
                            className={`
                              h-1.5
                              flex-1
                              rounded-full
                              ${
                                passwordStrength.level >=
                                level
                                  ? "bg-blue-500"
                                  : "bg-slate-100"
                              }
                            `}
                          />
                        ),
                      )}
                    </div>
                  </div>
                )}
              </FormField>

              {/* PASSWORD REQUIREMENTS */}

              {form.password && (
                <div
                  className="
                    rounded-2xl
                    border
                    border-slate-100
                    bg-slate-50/70
                    p-4
                  "
                >
                  <p
                    className="
                      text-[11px]
                      font-bold
                      text-slate-700
                    "
                  >
                    Password requirements
                  </p>

                  <div
                    className="
                      mt-3
                      grid
                      gap-2
                      sm:grid-cols-2
                    "
                  >
                    <Requirement
                      valid={
                        form.password.length >=
                        8
                      }
                      text="At least 8 characters"
                    />

                    <Requirement
                      valid={
                        /[A-Z]/.test(
                          form.password,
                        )
                      }
                      text="One uppercase letter"
                    />

                    <Requirement
                      valid={
                        /[a-z]/.test(
                          form.password,
                        )
                      }
                      text="One lowercase letter"
                    />

                    <Requirement
                      valid={
                        /[0-9]/.test(
                          form.password,
                        )
                      }
                      text="One number"
                    />
                  </div>
                </div>
              )}

              {/* PIN */}

              {!isEdit && (
                <FormField
                  label="Security PIN"
                  required
                  error={
                    errors.pin
                  }
                  icon={KeyRound}
                >
                  <div className="relative">
                    <input
                      type={
                        showPin
                          ? "text"
                          : "password"
                      }
                      name="pin"
                      value={
                        form.pin
                      }
                      onChange={
                        handleChange
                      }
                      placeholder="Enter 4–6 digit PIN"
                      inputMode="numeric"
                      maxLength={6}
                      autoComplete="off"
                      className={`
                        ${inputClass(
                          "pin",
                        )}
                        pr-11
                        tracking-[0.28em]
                      `}
                      disabled={
                        submitting ||
                        loading
                      }
                    />

                    <button
                      type="button"
                      onClick={() =>
                        setShowPin(
                          (
                            value,
                          ) =>
                            !value,
                        )
                      }
                      className="
                        absolute
                        right-2
                        top-1/2
                        flex
                        h-8
                        w-8
                        -translate-y-1/2
                        items-center
                        justify-center
                        rounded-lg
                        text-slate-400
                        transition
                        hover:bg-slate-100
                        hover:text-slate-600
                      "
                      tabIndex={-1}
                      aria-label={
                        showPin
                          ? "Hide PIN"
                          : "Show PIN"
                      }
                    >
                      {showPin ? (
                        <EyeOff
                          size={16}
                        />
                      ) : (
                        <Eye
                          size={16}
                        />
                      )}
                    </button>
                  </div>

                  <div
                    className="
                      mt-2
                      flex
                      items-start
                      gap-2
                    "
                  >
                    <ShieldCheck
                      size={13}
                      className="
                        mt-0.5
                        shrink-0
                        text-blue-500
                      "
                    />

                    <p
                      className="
                        text-[10px]
                        leading-4
                        text-slate-400
                      "
                    >
                      Required for staff account
                      authentication. The PIN is
                      stored securely as a hash and
                      is never saved as plain text.
                    </p>
                  </div>
                </FormField>
              )}

              {/* EDIT MODE SECURITY NOTICE */}

              {isEdit && (
                <div
                  className="
                    flex
                    items-start
                    gap-3
                    rounded-2xl
                    border
                    border-slate-100
                    bg-slate-50/70
                    p-4
                  "
                >
                  <div
                    className="
                      flex
                      h-8
                      w-8
                      shrink-0
                      items-center
                      justify-center
                      rounded-lg
                      bg-white
                      text-slate-500
                      shadow-sm
                    "
                  >
                    <KeyRound
                      size={15}
                    />
                  </div>

                  <div>
                    <p
                      className="
                        text-[11px]
                        font-bold
                        text-slate-700
                      "
                    >
                      Security credentials protected
                    </p>

                    <p
                      className="
                        mt-0.5
                        text-[10px]
                        leading-4
                        text-slate-400
                      "
                    >
                      Existing password and PIN
                      credentials are not displayed
                      while editing staff details.
                    </p>
                  </div>
                </div>
              )}

              {/* SECURITY NOTICE */}

              <div
                className="
                  flex
                  items-start
                  gap-3
                  rounded-2xl
                  border
                  border-blue-100
                  bg-blue-50/60
                  p-4
                "
              >
                <div
                  className="
                    flex
                    h-8
                    w-8
                    shrink-0
                    items-center
                    justify-center
                    rounded-lg
                    bg-white
                    text-blue-600
                    shadow-sm
                  "
                >
                  <ShieldCheck
                    size={16}
                  />
                </div>

                <div>
                  <p
                    className="
                      text-[11px]
                      font-bold
                      text-blue-900
                    "
                  >
                    Secure Staff Credentials
                  </p>

                  <p
                    className="
                      mt-0.5
                      text-[10px]
                      leading-4
                      text-blue-800/65
                    "
                  >
                    Passwords and PINs should
                    never be shared with other
                    staff members.
                  </p>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>

      {/* =================================================
          FOOTER ACTIONS
      ================================================= */}

      <div
        className="
          shrink-0
          border-t
          border-slate-100
          bg-white
          px-6
          py-4
        "
      >
        <div
          className="
            flex
            flex-col-reverse
            gap-2
            sm:flex-row
            sm:justify-end
          "
        >
          <button
            type="button"
            onClick={
              onCancel
            }
            disabled={
              submitting ||
              loading
            }
            className="
              inline-flex
              h-10
              items-center
              justify-center
              gap-2
              rounded-xl
              border
              border-slate-200
              bg-white
              px-4
              text-xs
              font-semibold
              text-slate-600
              transition
              hover:bg-slate-50
              disabled:cursor-not-allowed
              disabled:opacity-50
            "
          >
            <X
              size={14}
            />

            Cancel
          </button>

          <button
            type="submit"
            disabled={
              submitting ||
              loading
            }
            className="
              inline-flex
              h-10
              items-center
              justify-center
              gap-2
              rounded-xl
              bg-gradient-to-r
              from-blue-600
              to-indigo-600
              px-5
              text-xs
              font-semibold
              text-white
              shadow-lg
              shadow-blue-500/20
              transition
              hover:-translate-y-0.5
              hover:shadow-blue-500/25
              disabled:cursor-not-allowed
              disabled:opacity-60
              disabled:hover:translate-y-0
            "
          >
            {submitting ? (
              <>
                <span
                  className="
                    h-3.5
                    w-3.5
                    animate-spin
                    rounded-full
                    border-2
                    border-white/30
                    border-t-white
                  "
                />

                Saving...
              </>
            ) : (
              <>
                <CheckCircle2
                  size={14}
                />

                {isEdit
                  ? "Save Changes"
                  : `Create ${role}`}
              </>
            )}
          </button>
        </div>
      </div>
    </form>
  );
}

// =====================================================
// SECTION HEADING
// =====================================================

function SectionHeading({
  title,
  description,
}: {
  title: string;
  description: string;
}) {
  return (
    <div>
      <h3
        className="
          text-xs
          font-bold
          uppercase
          tracking-[0.14em]
          text-slate-700
        "
      >
        {title}
      </h3>

      <p
        className="
          mt-1
          text-[10px]
          text-slate-400
        "
      >
        {description}
      </p>
    </div>
  );
}

// =====================================================
// FORM FIELD
// =====================================================

function FormField({
  label,
  required = false,
  error,
  icon: Icon,
  children,
}: {
  label: string;
  required?: boolean;
  error?: string;
  icon?: typeof UserRound;
  children: ReactNode;
}) {
  return (
    <div>
      <label
        className="
          mb-1.5
          flex
          items-center
          gap-1.5
          text-[11px]
          font-semibold
          text-slate-700
        "
      >
        {Icon && (
          <Icon
            size={13}
            className="text-slate-400"
          />
        )}

        <span>
          {label}
        </span>

        {required && (
          <span className="text-rose-500">
            *
          </span>
        )}
      </label>

      {children}

      {error && (
        <p
          className="
            mt-1.5
            text-[10px]
            font-medium
            text-rose-600
          "
        >
          {error}
        </p>
      )}
    </div>
  );
}

// =====================================================
// REQUIREMENT
// =====================================================

function Requirement({
  valid,
  text,
}: {
  valid: boolean;
  text: string;
}) {
  return (
    <div className="flex items-center gap-2">
      <div
        className={`
          flex
          h-4
          w-4
          shrink-0
          items-center
          justify-center
          rounded-full
          ${
            valid
              ? "bg-emerald-100 text-emerald-600"
              : "bg-slate-100 text-slate-300"
          }
        `}
      >
        <CheckCircle2
          size={10}
        />
      </div>

      <span
        className={`
          text-[10px]
          ${
            valid
              ? "font-medium text-emerald-700"
              : "text-slate-400"
          }
        `}
      >
        {text}
      </span>
    </div>
  );
}